version: "2"
services:
    send:
        build: .
        links:
          - rabbitmq
        depends_on:
          - rabbitmq
        environment:
          - AMPQ_ADDRESS=amqp://rabbitmq:5672
        command: php send.php
        entrypoint: sh wait_for rabbitmq 5672

    receive:
        build: .
        links:
          - rabbitmq
        environment:
          - AMPQ_ADDRESS=amqp://rabbitmq:5672
        command: php receive.php
        entrypoint: sh wait_for rabbitmq 5672

    filter:
        build: .
        links:
          - rabbitmq
        environment:
          - AMPQ_ADDRESS=amqp://rabbitmq:5672
        command: php filter.php
        entrypoint: sh wait_for rabbitmq 5672

    rabbitmq:
        image: rabbitmq:alpine
        ports:
          - 5672
